Repository class
friedow/bpd pull request #17
Opened 2017-04-23 09:14 UTC by MaximilianV

this PR should fix several issues:
 - To many unnecessary requests were made
 - Lanes didn't update properly
 - Magically there were several masters after pushing a new branch 🦄

2017-04-23 11:04 UTC, friedow requested changes

2017-04-23 11:04 UTC, friedow commented on src/Overview/ProjectLane/BranchCard/BranchCard.js
> +        this.state = {branchName: this.props.branch.getName(),
Please break this line and fix the indentation.

2017-04-23 11:04 UTC, friedow commented on src/Overview/ProjectLane/BranchCard/BranchCard.js
> +            this.setState({issueNumber: props.branch.getIssueNumber(), issueDescription: props.branch.getIssueName()});
Please break this line after { and ,

2017-04-23 11:04 UTC, friedow commented on src/Overview/ProjectLane/BranchCard/BranchCard.js
> +            return "grey darken-2";
We should consider moving color definitions to a config file

2017-04-23 11:04 UTC, friedow commented on src/Overview/ProjectLane/BranchCard/BranchCard.js
> +                            <TextLane value={`</> ${this.state.branch.getNiceSonarqubeString()}`} color={this.getColorBasedOnQualityGate()} />
Please break this and the following 2 lines. 
Corresponding code convention: If a component initialises with 2 or more parameters, insert a line break before each parameter.

2017-04-23 16:45 UTC, MaximilianV commented on src/Overview/ProjectLane/BranchCard/BranchCard.js
> +            return "grey darken-2";
You are right, but I didn't want to do this in this refactoring branch :) But we should definitely consider some constants here.

2017-04-24 07:23 UTC, friedow approved these changes

2017-04-24 07:23 UTC, merged